club_alert:
  message: The 2026 Adult Learn to Sail course has been canceled
  details_url: adult-sailing.html
  details_label: View class details

events:
  spring_regatta:
    start: 2026-04-25
    end: 2026-04-25
  summer_sailstice:
    start: 2026-06-20
    end: 2026-06-20
  centerboard_slam:
    start: 2026-09-19
    end: 2026-09-19
  fall_regatta:
    start: 2026-10-10
    end: 2026-10-11

wednesday_racing:
  year: 2026
  current_series: summer
  spring_url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vR0cVSj0bM4DrF3I04OvYi8ri_FQTqH7mRXct4WmFF_C19LYzCZp_7pIdI2mKzUlqNRbZQkaQsGDqQR/pubhtml?widget=true&amp;headers=false"
  summer_url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vScegj4ECSbGcIEzdbNxcZgzKRlBn1nKEeaxjvHptZvSJj6d_BsoptCTZXaZOFTzuutk3pagE3oJfLQ/pubhtml?widget=true&amp;headers=false"
  fall_url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vQ13uqT8ihMF2CMobyH5gyi9JT7Dmwp3t9UAODJzYk1Pt08w-1ohSIuu7-DgrOjCB00-ecOtj3sHmbE/pubhtml?widget=true&amp;headers=false"
